import type { LanguageModel, ModelMessage, ToolSet } from 'ai';
import type { McpServerConfig } from './mcp.js';

// Progress events emitted during agent execution
export interface ProgressEvent {
  type:
    | 'thinking'
    | 'tool-call'
    | 'tool-result'
    | 'text'
    | 'step-complete'
    | 'done'
    | 'error'
    | 'debug';
  content: string;
  toolName?: string;
  toolArgs?: unknown;
  /**
   * Structured debug payload for `type === 'debug'` events. See
   * {@link DebugEvent} for the per-channel shape. Only populated when
   * `AgentConfig.debug` is set. Progress consumers that don't care
   * about debug can filter `type === 'debug'` out.
   */
  debug?: DebugEvent;
  /**
   * Full raw tool result. Only populated on `tool-result` events when the
   * agent was created with `emitFullResult: true`. See issue #48.
   *
   * Default behaviour emits only `summary` + `data` so secrets / large
   * file contents don't leak through logs and telemetry.
   */
  toolResult?: unknown;
  /**
   * Short human-readable summary of a `tool-result` event. Includes paths,
   * sizes, error codes — safe for operator logs; not intended for the model.
   */
  summary?: string;
  /**
   * Structured metadata about the tool invocation (tool-specific keys like
   * `path`, `bytes`, `matchCount`). Stable enough for programmatic consumers.
   */
  data?: Record<string, unknown>;
  /** True when a `tool-result` represents a blocked / denied operation. */
  blocked?: boolean;
  step?: number;
  totalSteps?: number;
}

// ─── Debug / observability (#72) ────────────────────────────────────────

/**
 * Per-channel debug event. See {@link DebugConfig} for how to opt in.
 *
 * The event surface is deliberately narrow and non-abstract — each
 * channel matches one thing you'd want to grep for when diagnosing
 * prompt / caching / tool-call problems. If you need richer tracing,
 * wire {@link AgentConfig.debug.sink} to an OpenTelemetry span emitter
 * and keep the progress stream unchanged.
 */
export type DebugEvent =
  /** The resolved system prompt, emitted once per run before any model call. */
  | {
      channel: 'system-prompt';
      step: number;
      content: string;
      bytes: number;
      /** True when the body was clipped to `maxBodyBytes`. */
      truncated: boolean;
    }
  /** The full message list going into a single `streamText` call. */
  | {
      channel: 'messages';
      step: number;
      messages: ModelMessage[];
      bytes: number;
      truncated: boolean;
    }
  /** Metadata about the request about to go to the provider. */
  | {
      channel: 'request';
      step: number;
      model: string;
      toolCount: number;
      toolNames: string[];
      providerOptions?: Record<string, unknown>;
    }
  /** A single raw stream part coming back from the provider. */
  | {
      channel: 'response-part';
      step: number;
      partType: string;
      /**
       * The raw stream part verbatim (text-delta, tool-call, reasoning-delta,
       * finish, etc.). Only populated in `trace` level — at `debug` level
       * we emit the partType counter only to keep logs bounded.
       */
      part?: Record<string, unknown>;
    }
  /** Per-step token accounting, including cache breakdown. */
  | {
      channel: 'cache';
      step: number;
      /** Input tokens that hit the prompt cache (cheap). */
      cacheReadTokens: number;
      /** Input tokens that wrote a new cache entry (premium). */
      cacheWriteTokens: number;
      /** Input tokens not served from or written to the cache. */
      noCacheTokens: number;
      /** Output tokens generated by the model. */
      outputTokens: number;
      /** Provider-specific usage metadata, e.g. `providerMetadata.anthropic`. */
      providerMetadata?: Record<string, unknown>;
    };

/**
 * Debug / observability configuration. Set on {@link AgentConfig.debug}
 * to get a lower-level view than `--verbose` / `--show-content`.
 *
 * Channels map 1:1 to {@link DebugEvent.channel} values. `all: true` is a
 * convenience that turns every channel on. Channel-specific flags take
 * precedence over `all` only in the sense that `all` is the baseline;
 * there's no way to "all-except" a channel intentionally — callers who
 * want that just list the channels they want explicitly.
 */
export interface DebugConfig {
  /** Log the resolved system prompt once per run. */
  systemPrompt?: boolean;
  /** Log the full message list before each model call. */
  messages?: boolean;
  /** Log request metadata (model, tool count, provider options). */
  request?: boolean;
  /**
   * Log raw stream parts returned by the provider. At `level: 'debug'` a
   * compact summary (partType only) is emitted; at `'trace'` the whole
   * part is attached. See `DebugConfig.traceResponseParts`.
   */
  response?: boolean;
  /** Log per-step cache read/write/no-cache token breakdown. */
  cache?: boolean;
  /** Turn every channel on. */
  all?: boolean;
  /**
   * When `response` is on, emit the full raw stream part object as
   * well as the partType. Off by default because stream parts can be
   * large; turn on when you specifically need to see them.
   */
  traceResponseParts?: boolean;
  /**
   * Cap the byte size of system-prompt / messages bodies in debug
   * events. Bodies exceeding this are truncated with a `truncated:
   * true` marker. Default: `16 * 1024` (16 KB).
   */
  maxBodyBytes?: number;
  /**
   * Where to send debug events. Default: they're also emitted as
   * `type: 'debug'` progress events so existing stream consumers can
   * see them. Provide a sink to route somewhere separate (e.g. a file
   * logger, stderr formatter, OpenTelemetry span emitter) — the sink
   * is called *in addition to* the progress event path.
   */
  sink?: (event: DebugEvent) => void | Promise<void>;
}

// Skill definition
export interface Skill {
  id: string;
  name: string;
  description: string;
  content: string; // The actual skill instructions
  author?: string;
  version?: string;
  /**
   * Verbatim user phrases that should trigger this skill. Concatenated into
   * the description when the manifest is built, so substring matching picks
   * up how users actually phrase requests (not just how authors name skills).
   * See issue #74 — addresses the "skills never fire because descriptions
   * don't match the user's voice" problem.
   */
  triggers?: string[];
}

/**
 * A search result returned by `SkillStore.search()`.
 *
 * Deliberately does **not** include a `url` field. Earlier drafts of the
 * interface carried `url?: string` and signalled "external skill registries
 * are fine to wire up." That's an SSRF / supply-chain footgun (see #34): a
 * hostile registry could return a URL the agent then auto-fetches with the
 * user's credentials. If you need URL-backed skill registries, build them
 * outside this interface, gate behind an explicit host allowlist, require
 * HTTPS, and never auto-install — `install()` must always receive the
 * verified content directly.
 */
export interface SkillSearchResult {
  id: string;
  name: string;
  description: string;
}

/**
 * Storage interface for skill definitions.
 *
 * Implementations are expected to be local (in-memory, OPFS, IndexedDB,
 * SQLite, …). External / network-backed implementations must not auto-fetch
 * skill content from `search()` results — see {@link SkillSearchResult}.
 */
export interface SkillStore {
  list(): Promise<Skill[]>;
  get(skillId: string): Promise<Skill | undefined>;
  install(skill: Skill): Promise<void>;
  remove(skillId: string): Promise<void>;
  search(query: string): Promise<SkillSearchResult[]>;
}

// ─── Routines (#77) ─────────────────────────────────────────────────────

/**
 * A routine input arg. Kept minimal — routines are prompts, not
 * typed DSLs. `optional` lets the routine author flag args that can be
 * omitted without failing; the model sees the metadata and can ask
 * the user for required args before calling `run_routine`.
 */
export interface RoutineInput {
  name: string;
  description?: string;
  optional?: boolean;
}

/**
 * A saved routine — a named procedure the agent can invoke by id.
 *
 * Routines differ from skills in *how they fire*: skills match against
 * task intent autonomously; routines are invoked explicitly by name
 * via `run_routine(id, args)`. They share the markdown-with-frontmatter
 * storage shape. See issue #77.
 */
export interface Routine {
  id: string;
  name: string;
  description: string;
  /** The routine body — markdown prompt, may contain `{{arg}}` placeholders. */
  body: string;
  inputs?: RoutineInput[];
  version?: string;
  /** Incremented every time the routine is invoked via `run_routine`. */
  runCount: number;
  /** ISO timestamp of the most recent invocation. Undefined for never-run. */
  lastRun?: string;
}

/**
 * Storage interface for routines.
 *
 * Implementations are expected to be local (in-memory, filesystem,
 * SQLite, …). Run metadata (`runCount`, `lastRun`) is tracked by the
 * store so a future agent-proposed capture pass can detect "I've done
 * this N times" without the agent having to maintain state.
 */
export interface RoutineStore {
  list(): Promise<Routine[]>;
  get(id: string): Promise<Routine | undefined>;
  save(routine: Routine): Promise<void>;
  remove(id: string): Promise<void>;
  /** Increment runCount and stamp lastRun. No-op if the routine doesn't exist. */
  recordRun(id: string): Promise<void>;
}

// ─── Scheduled tasks (#79) ──────────────────────────────────────────────

/**
 * A declarative scheduled task — a cron-driven agent run.
 *
 * Scheduled tasks turn agent-do into something closer to a long-running
 * colleague: inbox sweeps every 15 min, daily prep at 2am, weekly digest
 * on Sunday. Define them on {@link AgentConfig.scheduledTasks} and the
 * CLI / scheduler primitive will invoke them at the right time.
 *
 * The runtime does **not** itself daemonise — `scheduledTasks` is a
 * configuration primitive. Two execution surfaces use it:
 *
 * - `runScheduledTask(agent, task)` — fire a single task now, acquiring
 *   its lock file to prevent overlap with an already-running copy.
 * - `runScheduler(agent, tasks, options?)` — a foreground loop that
 *   ticks once per minute and fires any task whose cron expression
 *   matches.
 *
 * For production, most users will install a crontab entry per task
 * (via `agent-do scheduled-tasks install`) that calls
 * `agent-do scheduled-tasks run <id>` — the OS scheduler owns the
 * cadence, agent-do owns the lock file and logging.
 */
export interface ScheduledTask {
  /**
   * Unique task ID within this agent. Used as the lock-file name and
   * the handle for `agent-do scheduled-tasks run <id>`. Must match
   * `/^[a-zA-Z0-9_-]+$/` so it's safe as a filename.
   */
  id: string;
  /**
   * Standard 5-field cron expression (minute, hour, day-of-month,
   * month, day-of-week). Supports star, numeric, range, list, and
   * step forms — see `parseCron` in `src/scheduled-tasks.ts` for the
   * exact grammar. Numeric fields only; named months / weekdays are
   * not supported. Sunday is `0` (Saturday is `6`); `7` is also
   * accepted as Sunday for crontab compatibility.
   */
  cron: string;
  /**
   * Where the task's output goes:
   *
   * - `'isolated'` (default) — a fresh session. The task runs with no
   *   prior conversation history; good for stateless sweeps and
   *   digests.
   * - `'main'` — the task's output flows into the agent's main
   *   conversation. The caller is responsible for persisting and
   *   replaying that history (the scheduler just runs the turn); this
   *   is a primitive that higher-level hosts can build on.
   */
  sessionTarget?: 'isolated' | 'main';
  /**
   * How the payload is delivered to the agent:
   *
   * - `'agentTurn'` (default) — payload is injected as a user message,
   *   triggering a normal agent turn. Use for "please do X" prompts.
   * - `'systemEvent'` — payload is wrapped in a `<system-event>` envelope
   *   and the agent is invited to respond only when there's something
   *   to say (the "OK silence" contract). Use for heartbeat-style
   *   wakes.
   */
  wakeMode?: 'agentTurn' | 'systemEvent';
  /**
   * The payload delivered to the agent. Strings are used verbatim;
   * objects are serialised to JSON inside the envelope so the model
   * sees structured data.
   */
  payload: string | Record<string, unknown>;
  /**
   * Optional per-task description, shown in `scheduled-tasks status`
   * output.
   */
  description?: string;
}

/**
 * Persisted run record for a scheduled task. One entry per task ID,
 * updated on each run. Stored in `.agent-do/scheduler/status.json`.
 */
export interface ScheduledTaskStatus {
  id: string;
  /** ISO timestamp of the most recent run start. */
  lastRun?: string;
  /** ISO timestamp of the most recent run completion. */
  lastFinished?: string;
  /** 'success' | 'failed' | 'skipped' (lock held) | 'running'. */
  lastStatus?: 'success' | 'failed' | 'skipped' | 'running';
  /** Wall-clock duration of the most recent completed run. */
  durationMs?: number;
  /** Error message, set when `lastStatus === 'failed'`. */
  lastError?: string;
  /** Number of successful runs observed. */
  successCount?: number;
  /** Number of failed runs observed. */
  failureCount?: number;
}

// Usage record
export interface UsageRecord {
  timestamp: string;
  step: number;
  inputTokens: number;
  outputTokens: number;
  estimatedCost: number;
  model: string;
}

// Usage summary for a run
export interface RunUsage {
  totalInputTokens: number;
  totalOutputTokens: number;
  totalCost: number;
  steps: number;
  records: UsageRecord[];
}

// Permission levels
export type PermissionLevel = 'always' | 'ask' | 'never';
export type PermissionMode = 'accept-all' | 'deny-all' | 'ask';

export interface PermissionConfig {
  mode: PermissionMode;
  tools?: Record<string, PermissionLevel>; // per-tool overrides
  onPermissionRequest?: (request: {
    toolName: string;
    args: unknown;
  }) => Promise<boolean>;
}

// Hook events
export interface PreToolUseEvent {
  toolName: string;
  args: unknown;
  step: number;
}

export interface PostToolUseEvent {
  toolName: string;
  args: unknown;
  result: unknown;
  step: number;
  durationMs: number;
}

export interface StepStartEvent {
  step: number;
  totalSteps: number;
  tokensSoFar: number;
  costSoFar: number;
}

export interface StepCompleteEvent {
  step: number;
  hasToolCalls: boolean;
  text: string;
}

export interface CompleteEvent {
  result: string;
  totalSteps: number;
  usage: RunUsage;
  aborted: boolean;
}

// Hook decision
export interface HookDecision {
  decision: 'allow' | 'deny' | 'ask' | 'stop' | 'continue';
  reason?: string;
  modifiedArgs?: unknown; // for PreToolUse: modify the tool's input
}

// Hooks configuration
export interface AgentHooks {
  onPreToolUse?: (event: PreToolUseEvent) => Promise<HookDecision | void>;
  onPostToolUse?: (event: PostToolUseEvent) => Promise<void>;
  onStepStart?: (event: StepStartEvent) => Promise<HookDecision | void>;
  onStepComplete?: (event: StepCompleteEvent) => Promise<void>;
  onComplete?: (event: CompleteEvent) => Promise<void>;
  onUsage?: (record: UsageRecord) => Promise<void>;
}

// Pricing table
export type PricingTable = Record<string, { input: number; output: number }>;

// Agent configuration
export interface AgentConfig {
  id: string;
  name: string;
  model: LanguageModel;
  systemPrompt?: string; // Raw system prompt (CLAUDE.md content)
  tools?: ToolSet;
  /**
   * MCP (Model Context Protocol) servers to mount for this run (#75).
   *
   * Each entry spawns / connects to an MCP server; its tools are
   * namespaced as `mcp__<server>__<tool>` and merged into `tools`
   * before the loop starts. Permissions, hooks, usage tracking, and
   * `toolLimits` apply to MCP tools exactly as they do to local tools.
   *
   * The lifecycle is managed by the loop: servers are mounted once at
   * the start of each `run()` / `stream()` call and closed on
   * completion, abort, or error. See `src/mcp.ts` for transport
   * details (stdio, sse, streamable HTTP).
   */
  mcpServers?: McpServerConfig[];
  skills?: SkillStore;
  /**
   * Expose the privileged `install_skill` tool to the model (#24, H-05).
   *
   * Default **`false`**: the LLM cannot install skills, only search /
   * list / remove. Because installed skills get concatenated into the
   * system prompt on every subsequent run sharing the same store, a
   * prompt-injected agent with install access could rewrite its own
   * future instructions — a persistent jailbreak. Set `true` only when
   * the caller also runs a human-in-the-loop permission layer
   * (`permissions: { mode: 'ask' }` or `hooks.onPreToolUse`).
   */
  allowSkillInstall?: boolean;
  /**
   * Saved routines — named prompt-as-macro procedures (#77). When set,
   * the model gains `list_routines` and `run_routine(id, args)` tools
   * that surface and execute routines by name.
   */
  routines?: RoutineStore;
  /**
   * Expose the privileged `save_routine` tool to the model (#77).
   *
   * Default **`false`**: the LLM cannot save routines. Save is privileged
   * because a prompt-injected agent could persistently install a hostile
   * "routine" that future runs would execute when the user invokes it
   * by name. Same threat model as {@link allowSkillInstall}.
   */
  allowRoutineSave?: boolean;
  /**
   * How installed skills are injected into the system prompt (#74).
   *
   * - `'full'` — every skill's full body is dumped into the prompt (the
   *   pre-#74 behaviour). Good for small skill sets; works when the caller
   *   has counted the byte budget.
   * - `'manifest'` — only id / name / description (+ triggers) go in;
   *   bodies are fetched on demand via the `load_skill({ skillId })` tool.
   *   Essential for large skill libraries or cheaper models that can't
   *   absorb many skill bodies at once.
   * - `'auto'` (default) — start in `full`; switch to `manifest` once
   *   the combined skill bodies cross the `skillsManifestThreshold` byte
   *   budget. Gives the eager-load experience on tiny sets and the
   *   lazy-load experience on big ones without the caller choosing.
   */
  skillsMode?: 'full' | 'manifest' | 'auto';
  /**
   * Byte budget for the eager-load path in `skillsMode: 'auto'` (#74).
   * Default: `32 * 1024` (32 KB). Once the total of all skill bodies
   * exceeds this, auto-mode flips to `manifest`. Ignored for explicit
   * `skillsMode: 'full' | 'manifest'`.
   */
  skillsManifestThreshold?: number;
  maxIterations?: number;
  innerStepLimit?: number;
  hooks?: AgentHooks;
  permissions?: PermissionConfig;
  usage?: {
    enabled?: boolean;
    pricing?: PricingTable;
    limits?: {
      perRun?: number;
      perDay?: number;
    };
    /**
     * Hard cap multiplier for in-step cost checking (#31, M-07).
     *
     * `limits.perRun` is enforced in two layers with different timing:
     *
     * - **Soft limit (`perRun`)**: `UsageTracker.checkLimits()` runs
     *   at the top of each outer iteration. If an iteration's last
     *   step pushes cumulative cost over the soft limit, the loop
     *   breaks cleanly before the *next* iteration starts. One
     *   iteration's worth of spend may still be in flight when the
     *   soft check runs.
     *
     * - **Hard cap (`perRun × hardLimitMultiplier`)**: the per-step
     *   `onStepFinish` hook records each model step's usage and
     *   aborts the in-progress `streamText` call via AbortSignal as
     *   soon as cumulative cost crosses the hard cap. This bounds
     *   mid-iteration overshoot even in worst-case step chains.
     *
     * Default: `1.25` — gives the soft-limit check a comfortable
     * chance to fire between iterations before the hard cap does.
     */
    hardLimitMultiplier?: number;
    onLimitExceeded?: (event: {
      type: string;
      spent: number;
      limit: number;
    }) => Promise<boolean>;
  };
  /**
   * Per-run tool-call caps (#27, M-03).
   *
   * Without these, a runaway or prompt-injected agent can invoke thousands
   * of tool calls in a single outer iteration — `maxIterations` caps the
   * outer loop but `innerStepLimit` × unbounded-calls-per-step doesn't.
   *
   * - `maxToolCalls`: total cap across the entire run. Once exceeded,
   *   the wrapper returns a blocked `ToolResult` (with `reason:
   *   'tool-limit-run'`) rather than throwing; the model sees the
   *   error and can produce a final answer instead of crashing the
   *   loop.
   * - `maxToolCallsPerIteration`: resets at the start of each outer
   *   iteration. Same blocked-ToolResult semantics. Defends against
   *   tight per-iteration fan-out.
   *
   * Omit to disable (default). A sensible safe pair is `maxToolCalls: 100,
   * maxToolCallsPerIteration: 25`.
   */
  toolLimits?: {
    maxToolCalls?: number;
    maxToolCallsPerIteration?: number;
  };
  signal?: AbortSignal;
  /**
   * Include full raw tool results on `tool-result` progress events.
   *
   * Default (`false`): events carry only `summary` + structured `data`.
   * File contents, command output, and anything else the tool returned
   * stay out of the event stream. This keeps secrets out of CI logs and
   * telemetry by default.
   *
   * Set `true` when you need full fidelity for debugging or when you're
   * piping events to a trusted consumer that needs the raw payload.
   */
  emitFullResult?: boolean;
  /**
   * Number of recent outer iterations whose tool-output bodies are kept
   * verbatim in the conversation history. Older iterations get their
   * `<tool_output>...</tool_output>` bodies replaced with self-closing
   * markers, so injected content from a poisoned tool result can't
   * keep influencing the model on every subsequent step.
   *
   * Default `1` — only the most recent iteration's tool outputs flow in
   * full to the next call. The model still sees that the tool was
   * invoked (via the marker attributes) and the assistant's reasoning
   * about it, but the raw body is gone. See issue #33.
   *
   * Set to `Infinity` to keep the historical "everything stays in
   * context forever" behaviour.
   */
  historyKeepWindow?: number;
  /**
   * Declarative scheduled tasks (#79). Each entry binds a cron expression
   * to a payload that fires an agent run at its scheduled time.
   *
   * Validation happens once, at {@link createAgent} time: invalid cron
   * expressions, duplicate IDs, and unsafe task IDs throw synchronously
   * so misconfiguration fails loud. The runtime itself is optional —
   * declaring tasks does not automatically start a scheduler. Use
   * `runScheduler(agent, ...)` or install crontab entries via
   * `agent-do scheduled-tasks install` to actually drive them.
   */
  scheduledTasks?: ScheduledTask[];
  /**
   * Debug / observability hooks (#72). See {@link DebugConfig}.
   *
   * When set, the loop wraps `model` with a `wrapLanguageModel`
   * middleware that surfaces the resolved system prompt, the full
   * message list per step, per-step cache metrics, and (optionally)
   * every raw stream part. Events flow through the progress stream
   * as `type: 'debug'` and — if `debug.sink` is provided — to the
   * sink as well. No-op when `debug` is undefined, so there's zero
   * overhead for the default path.
   */
  debug?: DebugConfig;
}

// A message in conversation history
export interface ConversationMessage {
  role: 'user' | 'assistant';
  content: string;
}

// Filesystem store options
export interface FilesystemMemoryStoreOptions {
  /** Block all write operations. Agent can only read existing files. */
  readOnly?: boolean;
  /**
   * Called before any write/append/delete/mkdir operation.
   * Receives the canonicalized relative path (safe against ../ bypass).
   * Return true to allow, false to block.
   * Supports both sync and async callbacks.
   */
  onBeforeWrite?: (agentId: string, filePath: string, operation: 'write' | 'append' | 'delete' | 'mkdir') => boolean | Promise<boolean>;
}

// Agent instance
export interface Agent {
  readonly id: string;
  readonly name: string;
  run(task: string, context?: string, history?: ConversationMessage[]): Promise<string>;
  stream(task: string, context?: string, history?: ConversationMessage[]): AsyncIterable<ProgressEvent>;
  abort(): void;
}

// Run result
export interface RunResult {
  text: string;
  usage: RunUsage;
  steps: number;
  aborted: boolean;
}
